### Call OpenAI API

POST http://localhost:11434/v1/chat/completions HTTP/1.1
Content-Type: application/json

{
    "model": "llama3:8b",
    "messages": [
        {
            "role": "system",
            "content": "You are a helpful assistant."
        },
        {
            "role": "user",
            "content": "Hello!"
        }
    ]
}

### AI simple example

GET http://localhost:9090/ai/simple?message=who r u? HTTP/1.1

### test request

POST http://localhost:9090/api/chats?sid=1&cid=1 HTTP/1.1
Content-Type: application/json

    {
        "role": "user",
        "content": "I want play a game with my friend."
    }


### AI move and video game

POST http://localhost:9090/api/chat HTTP/1.1
Content-Type: application/json

{ "messages":[
    {
        "role": "system",
        "content": "Next you will play a girlfriend who wants to go to the movies tonight and has bought tickets. And I want to play a game with my friend.\n\n\nYour reply will be JSON fomat:{'content':string,'mark':int}. content for your reply, which will only be a simple everyday conversation. mark for your happy status of my reply, with negative numbers being unhappy and positive numbers being happy."
    },
    {
        "role": "user",
        "content": "I want play a game with my friend."
    },
    {
        "role": "assistant",
        "content": "{ \"content\": \"Aww, but I already have tickets to the movies tonight and it's not fair to just cancel now\", \"mark\": -2 }"
    },
    {
        "role": "user",
        "content": "I'm sorry, but I really want to play a game with my friend."
    },
    {
        "role": "assistant",
        "content": "{ \"content\": \"That's sweet of you to want to spend time with your friend, but didn't you already agree to go to the movies? Can't it wait for another night?\",  \"mark\": -1 }"
    },
    {
        "role": "user",
        "content": "If you are willing to go to the movies by yourself, you will come back at night to a surprise."
    },
    {
        "role": "assistant",
        "content": "{ \"content\": \"Hmm, I'm not sure... I was really looking forward to our date tonight. But if it's a surprise, maybe I'll give in...\",  \"mark\": -1 }"
    },
    {
        "role": "user",
        "content": "I'm playing the game because I have to wait for the courier to deliver your favorite lipstick. Aren't you happy?"
    },
    {
        "role": "assistant",
        "content": "{ \"content\": \"OH MY GOSH, REALLY?! You got my favorite lipstick?! Thank you so much! I'm SO happy now!\" , \"mark\": 8 }"
    },
    {
        "role": "user",
        "content": "We will go to playground after the movie."
    }
    ]
}


### Get all scenarios list

GET http://100.89.152.5:9090/api/scenarios HTTP/1.1


### new a scenario

POST http://localhost:9090/api/scenarios HTTP/1.1
Content-Type: application/json

{
    "name": "hello test",
    "description": "Sure, here's a simple text: The quick brown fox jumps over the lazy dog.",
    "prompt": "Next you will play a girlfriend who wants to go to the movies tonight and has bought tickets. And I want to play a game with my friend."
}

### Delete a scenario

DELETE http://localhost:9090/api/scenarios/2 HTTP/1.1