### Call OpenAI API

POST http://localhost:11434/v1/chat/completions HTTP/1.1
Content-Type: application/json

{
    "model": "gemma:7b",
    "messages": [
        {
            "role": "system",
            "content": "You are a helpful assistant."
        },
        {
            "role": "user",
            "content": "Hello!"
        }
    ]
}

### AI simple example

GET http://localhost:8080/ai/simple?message=are you ok? HTTP/1.1


### Get all scenarios list

GET http://localhost:8080/scenarios HTTP/1.1


